# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal_create_cpp <- function(cal) {
    .Call(`_calendarrr_cal_create_cpp`, cal)
}

cal_add_holiday_cpp <- function(cal_sexp, holidays) {
    .Call(`_calendarrr_cal_add_holiday_cpp`, cal_sexp, holidays)
}

cal_remove_holiday_cpp <- function(cal_sexp, holidays) {
    .Call(`_calendarrr_cal_remove_holiday_cpp`, cal_sexp, holidays)
}

cal_list_holidays_cpp <- function(cal_sexp, from, to, include_weekends) {
    .Call(`_calendarrr_cal_list_holidays_cpp`, cal_sexp, from, to, include_weekends)
}

rcpp_hello_world <- function() {
    .Call(`_calendarrr_rcpp_hello_world`)
}

