# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal_adjust_cpp <- function(cal, dates, convention) {
    .Call(`_calendarrr_cal_adjust_cpp`, cal, dates, convention)
}

cal_advance_cpp <- function(cal, dates, n, unit, convention, end_of_month = FALSE) {
    .Call(`_calendarrr_cal_advance_cpp`, cal, dates, n, unit, convention, end_of_month)
}

cal_business_days_between_cpp <- function(cal, from, to, include_first = TRUE, include_last = FALSE) {
    .Call(`_calendarrr_cal_business_days_between_cpp`, cal, from, to, include_first, include_last)
}

cal_end_of_month_cpp <- function(cal, dates) {
    .Call(`_calendarrr_cal_end_of_month_cpp`, cal, dates)
}

cal_list_holidays_cpp <- function(cal, from, to, include_weekends) {
    .Call(`_calendarrr_cal_list_holidays_cpp`, cal, from, to, include_weekends)
}

cal_is_weekend_cpp <- function(cal, dates) {
    .Call(`_calendarrr_cal_is_weekend_cpp`, cal, dates)
}

cal_is_business_day_cpp <- function(cal, dates) {
    .Call(`_calendarrr_cal_is_business_day_cpp`, cal, dates)
}

cal_is_holiday_cpp <- function(cal, dates) {
    .Call(`_calendarrr_cal_is_holiday_cpp`, cal, dates)
}

cal_is_end_of_month_cpp <- function(cal, dates) {
    .Call(`_calendarrr_cal_is_end_of_month_cpp`, cal, dates)
}

